# Copyright (c) 2026 Oxara Development
# All rights reserved.
#
# This source code and any related materials are the confidential and
# proprietary information of Oxara Development.
#
# Unauthorized copying, modification, distribution, use, or disclosure
# of this software, in whole or in part, is strictly prohibited without
# prior written permission from Oxara Development.
#
# Use is restricted to authorized members of the Oxara Development team.
# Any other use requires prior written approval from Oxara Development.

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

from rich import box
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

console = Console()


def extract_top_level_names(source: str) -> list[str]:
    """Extract all top-level class and variable names from a Python source string."""
    try:
        tree = ast.parse(source)
    except SyntaxError as e:
        raise ValueError(f'Syntax error: {e}') from e

    names = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef):
            names.append(node.name)
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    names.append(target.id)

    return names


def extract_base_exports(base_path: Path) -> list[str]:
    """Extract enum classes and their Enum() variable counterparts from base.py."""
    source = base_path.read_text('utf-8')
    try:
        tree = ast.parse(source)
    except SyntaxError as e:
        raise ValueError(f'Syntax error in base.py: {e}') from e

    exports = []
    for node in ast.iter_child_nodes(tree):
        # Enum subclasses
        if isinstance(node, ast.ClassDef):
            for base in node.bases:
                # Handle standard `Enum` (ast.Name) or `enum.Enum` (ast.Attribute)
                if isinstance(base, ast.Name) and base.id == 'Enum':
                    exports.append(node.name)
                elif isinstance(base, ast.Attribute) and base.attr == 'Enum':
                    exports.append(node.name)

        # Top-level assignments like FooEnum = Enum(...)
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id.endswith('Enum'):
                    exports.append(target.id)

    return exports


def extract_model_exports(path: Path) -> list[str]:
    """Extract top-level class names (models) from a schema file, excluding Base."""
    source = path.read_text('utf-8')
    try:
        tree = ast.parse(source)
    except SyntaxError as e:
        raise ValueError(f'Syntax error in {path.name}: {e}') from e

    return [node.name for node in ast.iter_child_nodes(tree) if isinstance(node, ast.ClassDef) and node.name != 'Base']


def generate_init(models_dir: Path) -> str:
    """Generate the __init__.py content from a models directory."""
    base_path = models_dir / 'base.py'
    if not base_path.exists():
        console.print('[bold red]✗ base.py not found in models directory.[/bold red]')
        sys.exit(1)

    # Collect all schema files (excluding base and __init__)
    schema_files = sorted(p for p in models_dir.glob('*.py') if p.name not in ('base.py', '__init__.py'))

    base_exports = extract_base_exports(base_path)
    module_exports: dict[str, list[str]] = {}

    tbl = Table(box=box.ROUNDED, border_style='cyan', show_header=True)
    tbl.add_column('Module', style='bold magenta')
    tbl.add_column('Exports', style='white')

    tbl.add_row('base', ', '.join(base_exports))

    for schema in schema_files:
        try:
            names = extract_model_exports(schema)
        except ValueError as e:
            console.print(f'[bold red]✗ {schema.name}: {e}[/bold red]')
            sys.exit(1)
        if names:
            module_exports[schema.stem] = names
            tbl.add_row(schema.stem, ', '.join(names))

    console.print()
    console.print(tbl)
    console.print()

    # Build the file
    lines: list[str] = [
        '# This file was autogenerated by db/scripts/genModels.py',
        '#',
        '# Copyright (c) 2026 dev-737',
        '#',
        '# This program is free software: you can redistribute it and/or modify',
        '# it under the terms of the GNU Affero General Public License as published',
        '# by the Free Software Foundation, either version 3 of the License, or',
        '# (at your option) any later version.',
        '#',
        '# This program is distributed in the hope that it will be useful,',
        '# but WITHOUT ANY WARRANTY; without even the implied warranty of',
        '# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the',
        '# GNU Affero General Public License for more details.',
        '#',
        '# You should have received a copy of the GNU Affero General Public License',
        '# along with this program.  If not, see <https://gnu.org>.',
        '',
    ]

    # Base imports
    lines.append('from .base import (')
    for name in base_exports:
        lines.append(f'    {name},')
    lines.append(')')

    # Per-module imports
    for module, names in module_exports.items():
        lines.append(f'from .{module} import (')
        for name in names:
            lines.append(f'    {name},')
        lines.append(')')

    lines.append('')

    # __all__
    lines.append('__all__ = [')

    # Base exports first
    lines.append('    # Base')
    for name in base_exports:
        lines.append(f"    '{name}',")

    # Per-module exports
    for module, names in module_exports.items():
        lines.append(f'    # {module.capitalize()} Domain')
        for name in names:
            lines.append(f"    '{name}',")

    lines.append(']')
    lines.append('')

    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate __init__.py from models directory.')
    parser.add_argument(
        'models_dir',
        nargs='?',
        default=str(Path(__file__).resolve().parent.parent.parent / 'dbSupport' / 'src' / 'models'),
        help='Path to the models directory. Defaults to ../src/models relative to this script.',
    )
    parser.add_argument('--dry-run', action='store_true', help='Print output without writing.')
    args = parser.parse_args()

    models_dir = Path(args.models_dir)

    if not models_dir.exists() or not models_dir.is_dir():
        console.print(f'[bold red]✗ Models directory not found: {models_dir}[/bold red]')
        sys.exit(1)

    console.print(f'[dim]Scanning: {models_dir}[/dim]')

    content = generate_init(models_dir)
    output_path = models_dir / '__init__.py'

    if args.dry_run:
        console.print(Panel(content, title='[bold]Generated __init__.py[/bold]', border_style='cyan', expand=False))
    else:
        output_path.write_text(content, 'utf-8')
        console.print(f'[bold green]✓ Written to {output_path}[/bold green]')
        console.print()
        console.print(Panel(content, title='[bold]Generated __init__.py[/bold]', border_style='green', expand=False))
